VERITESTERRAIN = "./veriteTerrain/"
XMLaCORRIGER = "./xmlPage-aCorriger/"
XMLCORRIGEES = "./xmlPage-corrigees/"
DICTCDS = "./py/dicos/correctionsCDS.json"
DICTPAGESNONCORR = "./py/dicos/aCorriger/"
DICTPAGESCORR = "./py/dicos/corriges/"
DICTGENERAL = "./py/dicos/general.json"