VERITESTERRAIN = "./veriteTerrain/"
XMLaCORRIGER = "./xmlPage-aCorriger/"
XMLCORRIGEES = "./xmlPage-corrigees/"
DICTCDS = "./py/dicos/corresp.json"
DICTPAGES = "./py/dicos/"
DICTGENERAL = "./py/dicos/general.json"