DICTCDS = "./py/dicos/correctionsCDS.json"
DICTPAGESNONCORR = "./py/dicos/aCorriger/"
DICTPAGESCORR = "./py/dicos/corriges/"
DICTGENERAL = "./py/dicos/general.json"
JOURNALREC = "./sources/journal-rec.json"
XMLaCORRIGER = "./predic-a-corriger/"
XMLCORRIGEES = "./predic-corrigees/"
VERITESTERRAIN = "./veriteTerrain/"