CdS02_Konv002-02_0065 = {'noeis': {'lemme': 'noies', 'contexte': 'me sont à NOIES es cousolr en'},
 'cousolr': {'lemme': 'couloir', 'contexte': 'à noeis es COULOIR en voyanst que'},
 'voyanst': {'lemme': 'voyant', 'contexte': 'es cousolr en VOYANT que cetxe qui'},
 'cetxe': {'lemme': 'cette', 'contexte': 'en voyanst que CETTE qui vours out'},
 'heureur': {'lemme': 'heureux', 'contexte': 'Mglis pes pluis HEUREUX que nous et'},
 'Chf': {'lemme': 'vhf', 'contexte': 'es mangeurs en VHF (les Mglis'},
 '(les': {'lemme': 'les', 'contexte': 'mangeurs en Chf LES Mglis'},
 'Mglis': {'lemme': 'glis', 'contexte': 'en Chf (les GLIS'},
 'nosition': {'lemme': 'position', 'contexte': 'd ans la POSITION la plus fachiense'},
 'fachiense': {'lemme': 'facheuse', 'contexte': 'nosition la plus FACHEUSE Coume tout ce'},
 'Coume': {'lemme': 'boume', 'contexte': 'la plus fachiense BOUME tout ce qui'},
 'quelires': {'lemme': 'quellres', 'contexte': 'la pronidence depuis QUELLRES anmes commence à'},
 'fadre': {'lemme': 'faire', 'contexte': 'commence à me FAIRE croire à la'},
 'pronidence': {'lemme': 'providence', 'contexte': 'croire à la PROVIDENCE'},
 'Catas': {'lemme': 'tatas', 'contexte': 'arrivera quelqu grande TATAS trapbe Erendnt'},
 'trapbe': {'lemme': 'trappe', 'contexte': 'quelqu grande Catas TRAPPE Erendnt'},
 'Erendnt': {'lemme': 'rendent', 'contexte': 'grande Catas trapbe RENDENT'},
 'Eangile': {'lemme': 'angle', 'contexte': 'oomme dit l ANGLE sene veun pas'},
 'péchear': {'lemme': 'pécheur', 'contexte': 'la mort du PÉCHEUR mais je'},
 'souhate': {'lemme': 'souhaite', 'contexte': 'connertire et leur SOUHAITE que la leçon'},
 'connertire': {'lemme': 'connerie', 'contexte': 'forte pour les CONNERIE et leur'},
 'intrêt': {'lemme': 'intérêt', 'contexte': 'sentire que leur INTÉRÊT est le mêmi'},
 'mêmi': {'lemme': 'même', 'contexte': 'intrêt est le MÊME que celu des'},
 'uplis': {'lemme': 'plis', 'contexte': 'que celu des PLIS la mutie'},
 'mutie': {'lemme': 'mutée', 'contexte': 'des uplis la MUTÉE'},
 'M': {'lemme': 'à', 'contexte': 'à un ouvrage À de Gataubraand trapaile'},
 'Gataubraand': {'lemme': 'Gataubraand', 'contexte': 'ouvrage M de GATAUBRAAND trapaile fauis ce'},
 'trapaile': {'lemme': 'travaile', 'contexte': 'M de Gataubraand TRAVAILE fauis ce momeae'},
 'fauis': {'lemme': 'fais', 'contexte': 'de Gataubraand trapaile FAIS ce momeae eu'},
 'momeae': {'lemme': 'momene', 'contexte': 'trapaile fauis ce MOMENE eu à un'},
 'fneur': {'lemme': 'fleur', 'contexte': 'epèrent bien en FLEUR de la liberti'},
 'Lui': {'lemme': 'qui', 'contexte': 'de la presse QUI it son parti'},
 'epèrent': {'lemme': 'espèrent', 'contexte': 'it son parti ESPÈRENT bien'},
 'acordée': {'lemme': 'accordée', 'contexte': 'elle leur est ACCORDÉE s on servrr'},
 'servrr': {'lemme': 'servir', 'contexte': 'acordée s on SERVIR poun ienverger la'},
 'ienverger': {'lemme': 'renverser', 'contexte': 'on servrr poun RENVERSER la srimstère la'},
 'srimstère': {'lemme': 'srimstère', 'contexte': 'poun ienverger la SRIMSTÈRE la'},
 'oustitutionnelle': {'lemme': 'constitutionnelle', 'contexte': 'faire ange charte CONSTITUTIONNELLE de et enpécher'},
 'enpécher': {'lemme': 'empécher', 'contexte': 'oustitutionnelle de et EMPÉCHER leuxs adpuisaves d'},
 'leuxs': {'lemme': 'leurs', 'contexte': 'de et enpécher LEURS adpuisaves d en'},
 'adpuisaves': {'lemme': 'adpuisaves', 'contexte': 'et enpécher leuxs ADPUISAVES d en faire'},
 'Ma': {'lemme': 'la', 'contexte': 'vous dre bemcour LA fainme se part'},
 'fainme': {'lemme': 'faine', 'contexte': 'dre bemcour Ma FAINE se part tres'},
 'cauge': {'lemme': 'cause', 'contexte': 'bien ll me CAUSE de vous dre'},
 'bemcour': {'lemme': 'belcour', 'contexte': 'de vous dre BELCOUR'},
 'Mres': {'lemme': 'tres', 'contexte': 'l d chases TRES deux fels vous'},
 'urgrespets': {'lemme': 'urgrespets', 'contexte': 'assurent de l URGRESPETS Mme Couraerni l'},
 'Mme': {'lemme': 'me', 'contexte': 'de l urgrespets ME Couraerni l'},
 'Couraerni': {'lemme': 'Couraerni', 'contexte': 'l urgrespets Mme COURAERNI l'},
 'entont': {'lemme': 'entant', 'contexte': 'point encore d ENTANT ni aparène d'},
 'aparène': {'lemme': 'adarène', 'contexte': 'd entont ni ADARÈNE d en avoir'},
 'trête': {'lemme': 'tête', 'contexte': 'est pas dine TÊTE'},
 'Vome': {'lemme': 'rome', 'contexte': 'elle sait ausse ROME saité e le'},
 'saité': {'lemme': 'sait', 'contexte': 'sait ausse Vome SAIT e le marage'},
 'marage': {'lemme': 'mariage', 'contexte': 'saité e le MARIAGE ne lu a'},
 'rélissi': {'lemme': 'réuissi', 'contexte': 'lu a pas RÉUISSI quoim elle sait'},
 'quoim': {'lemme': 'quoi', 'contexte': 'a pas rélissi QUOI elle sait ausse'},
 'ausse': {'lemme': 'aussi', 'contexte': 'quoim elle sait AUSSI'},
 'purense': {'lemme': 'pense', 'contexte': 'il tranoill au PENSE qu ene pusse'},
 'Caidraer': {'lemme': 'Caidraer', 'contexte': 'pusse l être CAIDRAER se porte bien'},
 'tranoill': {'lemme': 'traill', 'contexte': 'porte bien il TRAILL au'},
 'ffaume': {'lemme': 'ffame', 'contexte': 'joue à la FFAME de Je l'},
 'Je': {'lemme': 'de', 'contexte': 'que nous avons DE preble de votre'},
 'avaus': {'lemme': 'avais', 'contexte': 'de Je l AVAIS mis sur les'},
 'biaém': {'lemme': 'liam', 'contexte': 'les rangs pour LIAM ien'},
 'Cibre': {'lemme': 'libre', 'contexte': 'prenraidreles Mhoses je LIBRE mais grand j'},
 'prenraidreles': {'lemme': 'prenraidreles', 'contexte': 'la tournure qe PRENRAIDRELES Mhoses je'},
 'Mhoses': {'lemme': 'choses', 'contexte': 'tournure qe prenraidreles CHOSES je'},
 'domné': {'lemme': 'donné', 'contexte': 'visitie n ai DONNÉ auque suite à'},
 'auque': {'lemme': 'auquel', 'contexte': 'n ai domné AUQUEL suite à cela'},
 'visitie': {'lemme': 'visite', 'contexte': 'fait la moindre VISITE'},
 'guiffonage': {'lemme': 'griffonnage', 'contexte': 'lre tout le GRIFFONNAGE Les poriers'},
 'Les': {'lemme': 'les', 'contexte': 'tout le guiffonage LES poriers'},
 'poriers': {'lemme': 'portiers', 'contexte': 'le guiffonage Les PORTIERS'},
 'pulles': {'lemme': 'bulles', 'contexte': 'Prince et par BULLES m onc apprs'},
 'apprs': {'lemme': 'appris', 'contexte': 'pulles m onc APPRIS que votre Goues'},
 'Goues': {'lemme': 'joues', 'contexte': 'apprs que votre JOUES était redsema Prince'},
 'redsema': {'lemme': 'reema', 'contexte': 'votre Goues était REEMA Prince et par'},
 'Prince': {'lemme': 'prince', 'contexte': 'Goues était redsema PRINCE et par'},
 'Phincsse': {'lemme': 'Phincsse', 'contexte': 'que vous êtes PHINCSSE je Piuras d'},
 'Piuras': {'lemme': 'miuras', 'contexte': 'êtes Phincsse je MIURAS d apre cela'},
 'termmer': {'lemme': 'termier', 'contexte': 'd apre cela TERMIER'},
 'resprt': {'lemme': 'resort', 'contexte': 'des formules de RESORT I mai je'},
 'I': {'lemme': 'à', 'contexte': 'formules de resprt À mai je fais'},
 'tenvire': {'lemme': 'envie', 'contexte': 'tenvire abaecanent pais ENVIE abaecanent'},
 'abaecanent': {'lemme': 'abaecanent', 'contexte': 'abaecanent pais tenvire ABAECANENT'},
 '(Signé)': {'lemme': '(Signé)', 'contexte': ''},
 'Ctavier': {'lemme': 'tavier', 'contexte': '(Signé) Ctavier (Signé) TAVIER'},
 'Lettree': {'lemme': 'mettre', 'contexte': ''},
 'A': {'lemme': 'à', 'contexte': 'Prouchae caere Liedrg) À Mr Prouchae caere'},
 'Mr': {'lemme': 'dr', 'contexte': 'Mla complisent à DR Prous et à'},
 'Prouhae': {'lemme': 'Prouhae', 'contexte': 'Lidbeg) A Mr PROUHAE aehaude Lidbeg)'},
 'aehaude': {'lemme': 'chaude', 'contexte': 'A Mr Prouhae CHAUDE Lidbeg)'},
 'Lidbeg)': {'lemme': 'Lidbeg)', 'contexte': 'Mr Prouhae aehaude LIDBEG)'},
 'Dyck': {'lemme': 'wyck', 'contexte': '1a Mût 1824 WYCK le 1a Mût'},
 'Mût': {'lemme': 'fût', 'contexte': 'Dyck le 1a FÛT 1824'},
 'Dince': {'lemme': 'mince', 'contexte': 'restent deman l MINCE de Salm Prausein'},
 'Salm': {'lemme': 'palm', 'contexte': 'Cons tone de PALM'},
 'Prausein': {'lemme': 'fraulein', 'contexte': 'Dince de Salm FRAULEIN et sa fainille'},
 'fainille': {'lemme': 'farnille', 'contexte': 'Prausein et sa FARNILLE Ls restent deman'},
 'Ls': {'lemme': 'as', 'contexte': 'et sa fainille AS restent deman'},
 'vouleu': {'lemme': 'voulez', 'contexte': 'vous si vous VOULEZ tous venir augmenter'},
 'sgciété': {'lemme': 'société', 'contexte': 'augmenter la bonne SOCIÉTÉ vous vous'},
 'vrond': {'lemme': 'rond', 'contexte': 'à Lradbeng ferez ROND plaisir Sa Me'},
 'Sa': {'lemme': 'la', 'contexte': 'ferez vrond plaisir LA Me van der'},
 'Me': {'lemme': 'de', 'contexte': 'vrond plaisir Sa DE van der dein'},
 'Lradbeng': {'lemme': 'Lradbeng', 'contexte': 'enore demain à LRADBENG'},
 'engugeons': {'lemme': 'engageons', 'contexte': 'ciatre vous l ENGAGEONS à venir et'},
 'chergeons': {'lemme': 'chargeons', 'contexte': 'et nouis vous CHARGEONS de toutes les'},
 'ciatre': {'lemme': 'cintre', 'contexte': 'les ne ga CINTRE'},
 'Il': {'lemme': 'il', 'contexte': 'soir serait pofable IL fait un s'},
 'Muir': {'lemme': 'fuir', 'contexte': 'un s beau FUIR de lune que'},
 'pofable': {'lemme': 'potable', 'contexte': 'du soir serait POTABLE'},
 'touis': {'lemme': 'tous', 'contexte': 'je vous leise TOUS les maitres et'},
 'vrie': {'lemme': 'vie', 'contexte': 'journée le vous VIE sentement mon cher'},
 'sentement': {'lemme': 'sentiment', 'contexte': 'le vous vrie SENTIMENT mon cher voisin'},
 'repoise': {'lemme': 'repose', 'contexte': 'à la tele REPOSE de tous le'},
 'moide': {'lemme': 'monde', 'contexte': 'de tous le MONDE et de vous'},
 'Milr': {'lemme': 'ilr', 'contexte': 'd amié sincère ILR afraandes d amié'},
 'afraandes': {'lemme': 'friandes', 'contexte': 'amié sincère Milr FRIANDES d amié sincère'},
 '(Siigne': {'lemme': 'iigne', 'contexte': 'tone de Salm IIGNE Cons tone de'},
 'Cons': {'lemme': 'bons', 'contexte': 'de Salm (Siigne BONS tone de Salm'},
 'rptioions': {'lemme': 'retirions', 'contexte': 'à upresr coutes RETIRIONS faios j a'},
 'selit': {'lemme': 'salit', 'contexte': 'a vore le SALIT pire qui rpparter'},
 'rpparter': {'lemme': 'réparter', 'contexte': 'selit pire qui RÉPARTER à upresr'},
 'upresr': {'lemme': 'apres', 'contexte': 'qui rpparter à APRES'},
 'Letttre': {'lemme': 'metttre', 'contexte': ''},
 'Prouchae': {'lemme': 'rouche', 'contexte': 'Liedrg) A Mr ROUCHE caere Liedrg)'},
 'caere': {'lemme': 'cadre', 'contexte': 'A Mr Prouchae CADRE Liedrg)'},
 'Liedrg)': {'lemme': 'Liedrg)', 'contexte': 'Mr Prouchae caere LIEDRG)'},
 '(yack': {'lemme': 'yack', 'contexte': 'ja Aûet 1826 YACK ce ja Aûet'},
 'Aûet': {'lemme': 'et', 'contexte': '(yack ce ja ET 1826'},
 'Mla': {'lemme': 'la', 'contexte': 'sonaimable selesses sir LA complisent à Mr'},
 'complisent': {'lemme': 'compliment', 'contexte': 'selesses sir Mla COMPLIMENT à Mr Prous'},
 'Prous': {'lemme': 'trous', 'contexte': 'complisent à Mr TROUS et à sonaimable'},
 'sonaimable': {'lemme': 'inaimable', 'contexte': 'Prous et à INAIMABLE selesses sir'},
 'selesses': {'lemme': 'blesses', 'contexte': 'et à sonaimable BLESSES sir'},
 'eneor': {'lemme': 'encor', 'contexte': 'faire l a ENCOR Jenvoie savoir de'},
 'Jenvoie': {'lemme': 'envoie', 'contexte': 'l a eneor ENVOIE savoir de leurs'},
 'jauirai': {'lemme': 'jouirai', 'contexte': 'éaquele savoir si JOUIRAI le plaisir d'},
 'Sames': {'lemme': 'james', 'contexte': 'une de ces JAMES éaquele'},
 'éaquele': {'lemme': 'laquelle', 'contexte': 'de ces Sames LAQUELLE'},
 'dsape': {'lemme': 'sape', 'contexte': 'me voir et SAPE ses tunuis a'},
 'tunuis': {'lemme': 'tunis', 'contexte': 'et dsape ses TUNIS a'},
 'Dibaaic': {'lemme': 'Dibaaic', 'contexte': 'Dibaaic les viens DIBAAIC les viens'},
 'Ie': {'lemme': 'de', 'contexte': 'qulpu un ne DE suès toute en'},
 'suès': {'lemme': 'suis', 'contexte': 'un ne Ie SUIS toute en dair'},
 'pateudant': {'lemme': 'atendant', 'contexte': 'en dair atendant ATENDANT pas qulpu un'},
 'qulpu': {'lemme': 'qulp', 'contexte': 'atendant pateudant pas QULP un ne'},
 'sahaut': {'lemme': 'salaut', 'contexte': 'agresle compapie 8 SALAUT si je piserai'},
 'piserai': {'lemme': 'poserai', 'contexte': 'sahaut si je POSERAI pule ou ri'},
 'aureni': {'lemme': 'aureli', 'contexte': 'ou ri j AURELI une agresle compapie'},
 'agresle': {'lemme': 'agresse', 'contexte': 'j aureni une AGRESSE compapie 8'},
 'compapie': {'lemme': 'companie', 'contexte': 'aureni une agresle COMPANIE 8'},
 'esin': {'lemme': 'sein', 'contexte': 'ce qi 8et SEIN néontente de trut'},
 'néontente': {'lemme': 'contente', 'contexte': 'qi 8et esin CONTENTE de trut Mra'},
 'trut': {'lemme': 'tout', 'contexte': 'esin néontente de TOUT Mra ge je'},
 'Mra': {'lemme': 'ira', 'contexte': 'néontente de trut IRA ge je ne'},
 '8et': {'lemme': 'et', 'contexte': 'rer ce qi ET'},
 'Cain': {'lemme': 'main', 'contexte': '120) ( or MAIN 120)'},
 '120)': {'lemme': '120e', 'contexte': '( or Cain 120E'}}